# Generated by Django 2.2 on 2020-10-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturaant', '0004_auto_20201024_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.ManyToManyField(to='resturaant.Address'),
        ),
    ]
