# Generated by Django 2.2 on 2020-10-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturaant', '0005_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='type_of_address',
            field=models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('other', 'Other')], default='home', max_length=15),
        ),
    ]
