# Generated by Django 2.2 on 2020-10-24 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resturaant', '0011_auto_20201024_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_address', to='resturaant.Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('del', 'Delivered'), ('ndel', 'Not Delivered')], default='ndel', max_length=50),
        ),
    ]
