# Generated by Django 2.2 on 2020-10-24 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resturaant', '0014_order_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='feedback',
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_packaging', models.CharField(choices=[('1', 'Bad'), ('2', 'Good'), ('3', 'Excellent')], max_length=15)),
                ('food_taste', models.CharField(choices=[('1', 'Bad'), ('2', 'Good'), ('3', 'Excellent')], max_length=15)),
                ('delivery_services', models.CharField(choices=[('1', 'Bad'), ('2', 'Good'), ('3', 'Excellent')], max_length=15)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resturaant.Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_feedback', to='resturaant.Customer')),
            ],
        ),
    ]
