# Generated by Django 2.2 on 2020-10-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturaant', '0019_auto_20201024_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
