# Generated by Django 2.2 on 2020-10-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturaant', '0020_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
