# Generated by Django 2.2 on 2020-10-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturaant', '0021_cart_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Delivered', 'del'), ('Not Delivered', 'ndel')], default='ndel', max_length=50),
        ),
    ]
