# Generated by Django 2.2 on 2020-10-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturaant', '0022_auto_20201025_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('not Delivered', 'Not Delivered')], default='not Delivered', max_length=50),
        ),
    ]
