# Generated by Django 2.2 on 2020-10-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturaant', '0023_auto_20201025_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='other_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('del', 'Delivered'), ('ndel', 'Not Delivered')], default='ndel', max_length=50),
        ),
    ]
