# Generated by Django 2.2 on 2020-10-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturaant', '0024_auto_20201025_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=20)),
                ('percent_discount', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
    ]
