# Generated by Django 2.2 on 2020-10-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturaant', '0025_coupons'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='type_of_user',
            field=models.CharField(choices=[('both', 'Both'), ('normal', 'Normal'), ('premium', 'Premium')], default='premium', max_length=15),
        ),
    ]
