# Generated by Django 2.2 on 2020-10-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturaant', '0026_coupons_type_of_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='coupon_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupons',
            name='coupon_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='percent_discount',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
