# Generated by Django 2.2 on 2020-10-25 05:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resturaant', '0027_auto_20201025_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='expiry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
