# Generated by Django 2.2 on 2020-10-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturaant', '0028_coupons_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
