# Generated by Django 2.2 on 2020-10-25 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resturaant', '0029_auto_20201025_1109'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupons',
        ),
    ]
