# Generated by Django 2.2 on 2020-10-25 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resturaant', '0031_coupons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('not_completed', 'Not Completed')], default='not_completed', max_length=15)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coupon', to='resturaant.Coupons')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_discount', to='resturaant.Customer')),
            ],
        ),
    ]
