# Generated by Django 2.2 on 2020-10-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturaant', '0034_auto_20201025_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='meals',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
    ]
