# Generated by Django 2.2 on 2020-10-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturaant', '0035_meals_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='meals',
            name='meal_name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
