# Generated by Django 2.2 on 2020-10-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturaant', '0036_meals_meal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_items',
            name='max_quantity',
            field=models.IntegerField(default=50),
        ),
    ]
