# Generated by Django 2.2 on 2020-10-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturaant', '0038_auto_20201027_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_items',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food_items',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
