# Generated by Django 2.2 on 2020-10-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturaant', '0040_auto_20201027_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='meals',
            name='meal_end_time',
            field=models.TimeField(default='22:00:00'),
        ),
        migrations.AddField(
            model_name='meals',
            name='meal_start_time',
            field=models.TimeField(default='08:00:00'),
        ),
    ]
