# Generated by Django 2.2 on 2020-10-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturaant', '0042_daysoftheweek'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_items',
            name='days_of_avaibility',
            field=models.ManyToManyField(to='resturaant.DaysOfTheWeek'),
        ),
        migrations.AlterField(
            model_name='daysoftheweek',
            name='day_of_the_week',
            field=models.CharField(choices=[('Monday', '0'), ('Tuesday', '1'), ('Wednesday', '2'), ('Thursday', '3'), ('Friday', '4'), ('Saturday', '5'), ('Sunday', '6')], max_length=15),
        ),
    ]
