# Generated by Django 2.2 on 2020-10-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturaant', '0043_auto_20201027_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_items',
            name='days_of_avaibility',
            field=models.ManyToManyField(blank=True, null=True, to='resturaant.DaysOfTheWeek'),
        ),
    ]
