# Generated by Django 2.2 on 2020-10-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturaant', '0044_auto_20201027_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daysoftheweek',
            name='day_of_the_week',
            field=models.CharField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], max_length=15),
        ),
        migrations.AlterField(
            model_name='food_items',
            name='days_of_avaibility',
            field=models.ManyToManyField(to='resturaant.DaysOfTheWeek'),
        ),
    ]
